/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Thing = {
  _id: string
  _type: 'thing'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
  featuredImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
  featuredVideo?: MuxVideo
  featuredVideoThumb?: MuxVideo
  images?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }>
  videos?: Array<{
    file: MuxVideo
    title?: string
    alt?: string
    caption?: string
    poster?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    autoplay?: boolean
    loop?: boolean
    muted?: boolean
    _type: 'videoItem'
    _key: string
  }>
  isAiGenerated?: boolean
  body?: BlockContent
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & Youtube)
  | {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
      _key: string
    }
  | ({
      _key: string
    } & Callout)
  | ({
      _key: string
    } & MuxVideo)
  | ({
      _key: string
    } & FileBlock)
  | ({
      _key: string
    } & Table)
>

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type MuxVideo = {
  _type: 'mux.video'
  asset?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'mux.videoAsset'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Youtube = {
  _type: 'youtube'
  url: string
}

export type FileBlock = {
  _type: 'fileBlock'
  file: {
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    media?: unknown
    _type: 'file'
  }
  caption?: string
}

export type Callout = {
  _type: 'callout'
  tone?: 'neutral' | 'info' | 'success' | 'warning' | 'destructive'
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Topic = {
  _id: string
  _type: 'topic'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
  parent?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'topic'
  }
}

export type ReadingList = {
  _id: string
  _type: 'readingList'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  originalTitle?: string
  slug: Slug
  originalUrl: string
  discussionUrl?: string
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'category'
  }
  categories?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'category'
  }>
  topics?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'topic'
  }>
  featuredImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
  savedAt?: string
  detailedSummary?: string
  keyPoints?: Array<string>
  conclusion?: string
  shortSummary?: string
  gist?: string
  newTitle?: string
  discussionDetailedSummary?: string
  keyAgreeingViewpoints?: Array<string>
  keyOpposingViewpoints?: Array<string>
  sentiment?: string
  discussionShortSummary?: string
  discussionGist?: string
  discussionTitle?: string
  body?: BlockContent
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  subtitle?: string
  intro?: string
  excerpt: string
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  category?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'category'
  }
  mainImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
  hideMainImageOnPost?: boolean
  mainVideo?: MuxVideo
  publishedAt: string
  editedAt?: string
  body: BlockContent
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
  parent?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'category'
  }
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Table = {
  _type: 'table'
  rows?: Array<
    {
      _key: string
    } & TableRow
  >
}

export type TableRow = {
  _type: 'tableRow'
  cells?: Array<string>
}

export type MuxVideoAsset = {
  _id: string
  _type: 'mux.videoAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  status?: string
  assetId?: string
  playbackId?: string
  filename?: string
  thumbTime?: number
  data?: MuxAssetData
}

export type MuxAssetData = {
  _type: 'mux.assetData'
  resolution_tier?: string
  upload_id?: string
  created_at?: string
  id?: string
  status?: string
  max_stored_resolution?: string
  passthrough?: string
  encoding_tier?: string
  video_quality?: string
  master_access?: string
  aspect_ratio?: string
  duration?: number
  max_stored_frame_rate?: number
  mp4_support?: string
  max_resolution_tier?: string
  tracks?: Array<
    {
      _key: string
    } & MuxTrack
  >
  playback_ids?: Array<
    {
      _key: string
    } & MuxPlaybackId
  >
  static_renditions?: MuxStaticRenditions
}

export type MuxStaticRenditions = {
  _type: 'mux.staticRenditions'
  status?: string
  files?: Array<
    {
      _key: string
    } & MuxStaticRenditionFile
  >
}

export type MuxStaticRenditionFile = {
  _type: 'mux.staticRenditionFile'
  name?: string
  ext?: string
  height?: number
  width?: number
  bitrate?: number
  filesize?: string
  type?: string
  status?: string
  resolution_tier?: string
  resolution?: string
  id?: string
  passthrough?: string
}

export type MuxPlaybackId = {
  _type: 'mux.playbackId'
  id?: string
  policy?: string
}

export type MuxTrack = {
  _type: 'mux.track'
  id?: string
  type?: string
  max_width?: number
  max_frame_rate?: number
  duration?: number
  max_height?: number
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Thing
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | MuxVideo
  | Slug
  | Youtube
  | FileBlock
  | Callout
  | Topic
  | ReadingList
  | Post
  | Category
  | Author
  | Table
  | TableRow
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/models/blog.ts
// Variable: postsQuery
// Query: *[    _type == "post"    && defined(slug.current)  ]|order(publishedAt desc)[0...$limit]{    _id,     title,     slug,     publishedAt,     excerpt,     body[]{      ...,      _type == "mux.video" => {        asset->      }    },     category->{title, slug},     mainImage,     mainVideo{..., asset->},    author->{name, image}  }
export type PostsQueryResult = Array<{
  _id: string
  title: string
  slug: Slug
  publishedAt: string
  excerpt: string
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        _key: string
        _type: 'callout'
        tone?: 'destructive' | 'info' | 'neutral' | 'success' | 'warning'
        content?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: never
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'fileBlock'
        file: {
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
          }
          media?: unknown
          _type: 'file'
        }
        caption?: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
    | {
        _key: string
        _type: 'mux.video'
        asset: {
          _id: string
          _type: 'mux.videoAsset'
          _createdAt: string
          _updatedAt: string
          _rev: string
          status?: string
          assetId?: string
          playbackId?: string
          filename?: string
          thumbTime?: number
          data?: MuxAssetData
        } | null
      }
    | {
        _key: string
        _type: 'table'
        rows?: Array<
          {
            _key: string
          } & TableRow
        >
      }
    | {
        _key: string
        _type: 'youtube'
        url: string
      }
  >
  category: {
    title: string
    slug: Slug
  } | null
  mainImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  }
  mainVideo: {
    _type: 'mux.video'
    asset: {
      _id: string
      _type: 'mux.videoAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      status?: string
      assetId?: string
      playbackId?: string
      filename?: string
      thumbTime?: number
      data?: MuxAssetData
    } | null
  } | null
  author: {
    name: string
    image: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
}>
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug && category->slug.current == $categorySlug][0]{      _id,       title,       slug,       subtitle,       intro,       category->{title, slug},       publishedAt,       editedAt,       excerpt,       mainImage{..., "caption": caption},      hideMainImageOnPost,      mainVideo{..., asset->},      body[]{        ...,        _type == "mux.video" => {          asset->        }      },       author->{name, image}    }
export type PostQueryResult = {
  _id: string
  title: string
  slug: Slug
  subtitle: string | null
  intro: string | null
  category: {
    title: string
    slug: Slug
  } | null
  publishedAt: string
  editedAt: string | null
  excerpt: string
  mainImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption: string | null
    _type: 'image'
  }
  hideMainImageOnPost: boolean | null
  mainVideo: {
    _type: 'mux.video'
    asset: {
      _id: string
      _type: 'mux.videoAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      status?: string
      assetId?: string
      playbackId?: string
      filename?: string
      thumbTime?: number
      data?: MuxAssetData
    } | null
  } | null
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        _key: string
        _type: 'callout'
        tone?: 'destructive' | 'info' | 'neutral' | 'success' | 'warning'
        content?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: never
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'fileBlock'
        file: {
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
          }
          media?: unknown
          _type: 'file'
        }
        caption?: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
    | {
        _key: string
        _type: 'mux.video'
        asset: {
          _id: string
          _type: 'mux.videoAsset'
          _createdAt: string
          _updatedAt: string
          _rev: string
          status?: string
          assetId?: string
          playbackId?: string
          filename?: string
          thumbTime?: number
          data?: MuxAssetData
        } | null
      }
    | {
        _key: string
        _type: 'table'
        rows?: Array<
          {
            _key: string
          } & TableRow
        >
      }
    | {
        _key: string
        _type: 'youtube'
        url: string
      }
  >
  author: {
    name: string
    image: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
} | null

// Source: ./src/models/category.ts
// Variable: categoriesQuery
// Query: *[    _type == "category"    && count(*[_type == "readingList" && references(^._id)]) >= 5  ]|order(title asc){    _id,    title,    slug,    description  }
export type CategoriesQueryResult = Array<{
  _id: string
  title: string
  slug: Slug
  description: string | null
}>

// Source: ./src/models/readingList.ts
// Variable: readingListItemsQuery
// Query: *[    _type == "readingList"    && defined(slug.current)    && ($category == "" || $category in categories[]->slug.current)    && ($topic == "" || $topic in topics[]->slug.current)  ]|order(savedAt desc)[$start...$end]{    _id,    title,    slug,    originalUrl,    savedAt,    gist,    shortSummary,    keyPoints,    sentiment,    keyAgreeingViewpoints,    keyOpposingViewpoints,    categories[]->{title, slug},    topics[]->{_id, title, slug},    featuredImage  }
export type ReadingListItemsQueryResult = Array<{
  _id: string
  title: string
  slug: Slug
  originalUrl: string
  savedAt: string | null
  gist: string | null
  shortSummary: string | null
  keyPoints: Array<string> | null
  sentiment: string | null
  keyAgreeingViewpoints: Array<string> | null
  keyOpposingViewpoints: Array<string> | null
  categories: Array<{
    title: string
    slug: Slug
  }> | null
  topics: Array<{
    _id: string
    title: string
    slug: Slug
  }> | null
  featuredImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
  } | null
}>
// Variable: countQuery
// Query: count(*[    _type == "readingList"    && defined(slug.current)    && ($category == "" || $category in categories[]->slug.current)    && ($topic == "" || $topic in topics[]->slug.current)  ])
export type CountQueryResult = number
// Variable: readingListItemQuery
// Query: *[_type == "readingList" && slug.current == $slug][0]{      _id,       title,       originalTitle,      slug,       originalUrl,      discussionUrl,      categories[]->{title, slug},      topics[]->{_id, title, slug},      savedAt,       featuredImage{..., "caption": caption},      detailedSummary,      keyPoints,      conclusion,      shortSummary,      gist,      newTitle,      discussionDetailedSummary,      keyAgreeingViewpoints,      keyOpposingViewpoints,      sentiment,      discussionShortSummary,      discussionGist,      discussionTitle,      body[]{        ...,        _type == "mux.video" => {          asset->        }      }    }
export type ReadingListItemQueryResult = {
  _id: string
  title: string
  originalTitle: string | null
  slug: Slug
  originalUrl: string
  discussionUrl: string | null
  categories: Array<{
    title: string
    slug: Slug
  }> | null
  topics: Array<{
    _id: string
    title: string
    slug: Slug
  }> | null
  savedAt: string | null
  featuredImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption: string | null
    _type: 'image'
  } | null
  detailedSummary: string | null
  keyPoints: Array<string> | null
  conclusion: string | null
  shortSummary: string | null
  gist: string | null
  newTitle: string | null
  discussionDetailedSummary: string | null
  keyAgreeingViewpoints: Array<string> | null
  keyOpposingViewpoints: Array<string> | null
  sentiment: string | null
  discussionShortSummary: string | null
  discussionGist: string | null
  discussionTitle: string | null
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        _key: string
        _type: 'callout'
        tone?: 'destructive' | 'info' | 'neutral' | 'success' | 'warning'
        content?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: never
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'fileBlock'
        file: {
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
          }
          media?: unknown
          _type: 'file'
        }
        caption?: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
    | {
        _key: string
        _type: 'mux.video'
        asset: {
          _id: string
          _type: 'mux.videoAsset'
          _createdAt: string
          _updatedAt: string
          _rev: string
          status?: string
          assetId?: string
          playbackId?: string
          filename?: string
          thumbTime?: number
          data?: MuxAssetData
        } | null
      }
    | {
        _key: string
        _type: 'table'
        rows?: Array<
          {
            _key: string
          } & TableRow
        >
      }
    | {
        _key: string
        _type: 'youtube'
        url: string
      }
  > | null
} | null

// Source: ./src/models/thing.ts
// Variable: thingsQuery
// Query: *[    _type == "thing"  ]|order(_createdAt desc)[0...$limit]{    _id,    title,    slug,    description,    featuredImage{..., "caption": caption, "alt": alt},    featuredVideo{..., asset->},    featuredVideoThumb{..., asset->},    images[]{      ...,      "caption": caption,      "alt": alt    },    videos[]{      file{..., asset->},      title,      alt,      caption,      poster{..., "alt": alt},      autoplay,      loop,      muted    },    isAiGenerated,    body[]{      ...,      _type == "mux.video" => {        asset->      }    }  }
export type ThingsQueryResult = Array<{
  _id: string
  title: string
  slug: Slug
  description: string | null
  featuredImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string | null
    caption: string | null
    _type: 'image'
  }
  featuredVideo: {
    _type: 'mux.video'
    asset: {
      _id: string
      _type: 'mux.videoAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      status?: string
      assetId?: string
      playbackId?: string
      filename?: string
      thumbTime?: number
      data?: MuxAssetData
    } | null
  } | null
  featuredVideoThumb: {
    _type: 'mux.video'
    asset: {
      _id: string
      _type: 'mux.videoAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      status?: string
      assetId?: string
      playbackId?: string
      filename?: string
      thumbTime?: number
      data?: MuxAssetData
    } | null
  } | null
  images: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string | null
    caption: string | null
    _type: 'image'
    _key: string
  }> | null
  videos: Array<{
    file: {
      _type: 'mux.video'
      asset: {
        _id: string
        _type: 'mux.videoAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        status?: string
        assetId?: string
        playbackId?: string
        filename?: string
        thumbTime?: number
        data?: MuxAssetData
      } | null
    }
    title: string | null
    alt: string | null
    caption: string | null
    poster: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string | null
      _type: 'image'
    } | null
    autoplay: boolean | null
    loop: boolean | null
    muted: boolean | null
  }> | null
  isAiGenerated: boolean | null
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        _key: string
        _type: 'callout'
        tone?: 'destructive' | 'info' | 'neutral' | 'success' | 'warning'
        content?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: never
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'fileBlock'
        file: {
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
          }
          media?: unknown
          _type: 'file'
        }
        caption?: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
    | {
        _key: string
        _type: 'mux.video'
        asset: {
          _id: string
          _type: 'mux.videoAsset'
          _createdAt: string
          _updatedAt: string
          _rev: string
          status?: string
          assetId?: string
          playbackId?: string
          filename?: string
          thumbTime?: number
          data?: MuxAssetData
        } | null
      }
    | {
        _key: string
        _type: 'table'
        rows?: Array<
          {
            _key: string
          } & TableRow
        >
      }
    | {
        _key: string
        _type: 'youtube'
        url: string
      }
  > | null
}>
// Variable: thingQuery
// Query: *[_type == "thing" && slug.current == $slug][0]{      _id,      title,      slug,      description,      featuredImage{..., "caption": caption, "alt": alt},      featuredVideo{..., asset->},      featuredVideoThumb{..., asset->},      images[]{        ...,        "caption": caption,        "alt": alt      },      videos[]{        file{..., asset->},        title,        alt,        caption,        poster{..., "alt": alt},        autoplay,        loop,        muted      },      isAiGenerated,      body[]{        ...,        _type == "mux.video" => {          asset->        }      }    }
export type ThingQueryResult = {
  _id: string
  title: string
  slug: Slug
  description: string | null
  featuredImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string | null
    caption: string | null
    _type: 'image'
  }
  featuredVideo: {
    _type: 'mux.video'
    asset: {
      _id: string
      _type: 'mux.videoAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      status?: string
      assetId?: string
      playbackId?: string
      filename?: string
      thumbTime?: number
      data?: MuxAssetData
    } | null
  } | null
  featuredVideoThumb: {
    _type: 'mux.video'
    asset: {
      _id: string
      _type: 'mux.videoAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      status?: string
      assetId?: string
      playbackId?: string
      filename?: string
      thumbTime?: number
      data?: MuxAssetData
    } | null
  } | null
  images: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string | null
    caption: string | null
    _type: 'image'
    _key: string
  }> | null
  videos: Array<{
    file: {
      _type: 'mux.video'
      asset: {
        _id: string
        _type: 'mux.videoAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        status?: string
        assetId?: string
        playbackId?: string
        filename?: string
        thumbTime?: number
        data?: MuxAssetData
      } | null
    }
    title: string | null
    alt: string | null
    caption: string | null
    poster: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string | null
      _type: 'image'
    } | null
    autoplay: boolean | null
    loop: boolean | null
    muted: boolean | null
  }> | null
  isAiGenerated: boolean | null
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        _key: string
        _type: 'callout'
        tone?: 'destructive' | 'info' | 'neutral' | 'success' | 'warning'
        content?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: never
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'fileBlock'
        file: {
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
          }
          media?: unknown
          _type: 'file'
        }
        caption?: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
    | {
        _key: string
        _type: 'mux.video'
        asset: {
          _id: string
          _type: 'mux.videoAsset'
          _createdAt: string
          _updatedAt: string
          _rev: string
          status?: string
          assetId?: string
          playbackId?: string
          filename?: string
          thumbTime?: number
          data?: MuxAssetData
        } | null
      }
    | {
        _key: string
        _type: 'table'
        rows?: Array<
          {
            _key: string
          } & TableRow
        >
      }
    | {
        _key: string
        _type: 'youtube'
        url: string
      }
  > | null
} | null

// Source: ./src/models/topic.ts
// Variable: topicBySlugQuery
// Query: *[    _type == "topic"    && slug.current == $slug  ][0]{    _id,    title,    slug  }
export type TopicBySlugQueryResult = {
  _id: string
  title: string
  slug: Slug
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[\n    _type == "post"\n    && defined(slug.current)\n  ]|order(publishedAt desc)[0...$limit]{\n    _id, \n    title, \n    slug, \n    publishedAt, \n    excerpt, \n    body[]{\n      ...,\n      _type == "mux.video" => {\n        asset->\n      }\n    }, \n    category->{title, slug}, \n    mainImage, \n    mainVideo{..., asset->},\n    author->{name, image}\n  }': PostsQueryResult
    '*[_type == "post" && slug.current == $slug && category->slug.current == $categorySlug][0]{\n      _id, \n      title, \n      slug, \n      subtitle, \n      intro, \n      category->{title, slug}, \n      publishedAt, \n      editedAt, \n      excerpt, \n      mainImage{..., "caption": caption},\n      hideMainImageOnPost,\n      mainVideo{..., asset->},\n      body[]{\n        ...,\n        _type == "mux.video" => {\n          asset->\n        }\n      }, \n      author->{name, image}\n    }': PostQueryResult
    '*[\n    _type == "category"\n    && count(*[_type == "readingList" && references(^._id)]) >= 5\n  ]|order(title asc){\n    _id,\n    title,\n    slug,\n    description\n  }': CategoriesQueryResult
    '*[\n    _type == "readingList"\n    && defined(slug.current)\n    && ($category == "" || $category in categories[]->slug.current)\n    && ($topic == "" || $topic in topics[]->slug.current)\n  ]|order(savedAt desc)[$start...$end]{\n    _id,\n    title,\n    slug,\n    originalUrl,\n    savedAt,\n    gist,\n    shortSummary,\n    keyPoints,\n    sentiment,\n    keyAgreeingViewpoints,\n    keyOpposingViewpoints,\n    categories[]->{title, slug},\n    topics[]->{_id, title, slug},\n    featuredImage\n  }': ReadingListItemsQueryResult
    'count(*[\n    _type == "readingList"\n    && defined(slug.current)\n    && ($category == "" || $category in categories[]->slug.current)\n    && ($topic == "" || $topic in topics[]->slug.current)\n  ])': CountQueryResult
    '*[_type == "readingList" && slug.current == $slug][0]{\n      _id, \n      title, \n      originalTitle,\n      slug, \n      originalUrl,\n      discussionUrl,\n      categories[]->{title, slug},\n      topics[]->{_id, title, slug},\n      savedAt, \n      featuredImage{..., "caption": caption},\n      detailedSummary,\n      keyPoints,\n      conclusion,\n      shortSummary,\n      gist,\n      newTitle,\n      discussionDetailedSummary,\n      keyAgreeingViewpoints,\n      keyOpposingViewpoints,\n      sentiment,\n      discussionShortSummary,\n      discussionGist,\n      discussionTitle,\n      body[]{\n        ...,\n        _type == "mux.video" => {\n          asset->\n        }\n      }\n    }': ReadingListItemQueryResult
    '*[\n    _type == "thing"\n  ]|order(_createdAt desc)[0...$limit]{\n    _id,\n    title,\n    slug,\n    description,\n    featuredImage{..., "caption": caption, "alt": alt},\n    featuredVideo{..., asset->},\n    featuredVideoThumb{..., asset->},\n    images[]{\n      ...,\n      "caption": caption,\n      "alt": alt\n    },\n    videos[]{\n      file{..., asset->},\n      title,\n      alt,\n      caption,\n      poster{..., "alt": alt},\n      autoplay,\n      loop,\n      muted\n    },\n    isAiGenerated,\n    body[]{\n      ...,\n      _type == "mux.video" => {\n        asset->\n      }\n    }\n  }': ThingsQueryResult
    '*[_type == "thing" && slug.current == $slug][0]{\n      _id,\n      title,\n      slug,\n      description,\n      featuredImage{..., "caption": caption, "alt": alt},\n      featuredVideo{..., asset->},\n      featuredVideoThumb{..., asset->},\n      images[]{\n        ...,\n        "caption": caption,\n        "alt": alt\n      },\n      videos[]{\n        file{..., asset->},\n        title,\n        alt,\n        caption,\n        poster{..., "alt": alt},\n        autoplay,\n        loop,\n        muted\n      },\n      isAiGenerated,\n      body[]{\n        ...,\n        _type == "mux.video" => {\n          asset->\n        }\n      }\n    }': ThingQueryResult
    '*[\n    _type == "topic"\n    && slug.current == $slug\n  ][0]{\n    _id,\n    title,\n    slug\n  }': TopicBySlugQueryResult
  }
}
